# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-08 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clasevehiculo',
            fields=[
                ('descripcion', models.CharField(blank=True, max_length=60, null=True)),
                ('idclasev', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'clasevehiculo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Combustibles',
            fields=[
                ('nombrecomb', models.CharField(blank=True, max_length=60, null=True)),
                ('idcomb', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'combustibles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Provincias',
            fields=[
                ('nombreprov', models.CharField(blank=True, max_length=60, null=True)),
                ('idprov', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'provincias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipovehiculo',
            fields=[
                ('nombretipov', models.CharField(blank=True, max_length=60, null=True)),
                ('idtipov', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tipovehiculo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('placa', models.CharField(blank=True, max_length=15, null=True)),
                ('modelo', models.CharField(blank=True, max_length=6, null=True)),
                ('marca', models.CharField(blank=True, max_length=30, null=True)),
                ('tonelaje', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
                ('asientos', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
                ('idvehiculo', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'vehiculos',
                'managed': False,
            },
        ),
    ]
